import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/header";
import {Inter} from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider";
import { dark } from "@clerk/themes";

export const metadata = {
  title: "Sensai - AI Career Coach",
  description: "Generated by create next app",
};
const inter = Inter({subsets:["latin"]});

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      baseTheme:dark
    }}>
       <html lang="en" suppressHydrationWarning>
         <body
           className={`${inter.className}`}
         >
            <ThemeProvider
               attribute="class"
               defaultTheme="dark"
               enableSystem
               disableTransitionOnChange
             >
               <Header></Header>
               <main className="min-h-screen">{children}</main>
               <footer className="bg-muted/50 py-12">
                 <div className="container mx-auto px-4 text-center text-gray-200" >
                    <p>we </p>
                 </div>
               </footer>
             </ThemeProvider>
         </body>
       </html>
    </ClerkProvider>
  );
}
